// AI-powered Software Builder Frontend Controller
document.addEventListener("DOMContentLoaded", () => {
    // Current compiled application state
    let compiledAppState = null;
    let selectedSchemaType = "ui";
    let activeRuntimeRoute = "/login";
    let activeUserRole = "Admin";
    let mockJwtToken = null;

    // Elements
    const navItems = document.querySelectorAll(".nav-item");
    const tabPanes = document.querySelectorAll(".tab-pane");
    const pageTitle = document.getElementById("page-title");
    const pageSubtitle = document.getElementById("page-subtitle");
    
    const promptInput = document.getElementById("prompt-input");
    const compileBtn = document.getElementById("compile-btn");
    const apiOverrideToggle = document.getElementById("api-override-toggle");
    const consoleLogs = document.getElementById("console-logs");
    const graphContainer = document.getElementById("graph-container");
    
    const schemaBtns = document.querySelectorAll(".schema-btn");
    const schemaCodeBlock = document.getElementById("schema-code-block");
    const schemaViewerTitle = document.getElementById("schema-viewer-title");
    const copySchemaBtn = document.getElementById("copy-schema-btn");
    
    const valErrorsCount = document.getElementById("val-errors-count");
    const valWarningsCount = document.getElementById("val-warnings-count");
    const valStatusText = document.getElementById("val-status-text");
    const valStatusIcon = document.getElementById("val-status-icon");
    const auditLogList = document.getElementById("audit-log-list");
    
    const runtimeRoleSelect = document.getElementById("runtime-role-select");
    const simReportBox = document.getElementById("sim-report-box");
    const sandboxViewport = document.getElementById("sandbox-viewport");
    
    const loadingOverlay = document.getElementById("loading-overlay");
    const loadingTitle = document.getElementById("loading-title");
    const loadingSubtitle = document.getElementById("loading-subtitle");

    // --- Tab Navigation ---
    navItems.forEach(item => {
        item.addEventListener("click", () => {
            const targetTab = item.getAttribute("data-tab");
            
            navItems.forEach(n => n.classList.remove("active"));
            tabPanes.forEach(t => t.classList.remove("active"));
            
            item.classList.add("active");
            document.getElementById(targetTab).classList.add("active");
            
            // Update Page Titles
            if (targetTab === "compiler-tab") {
                pageTitle.textContent = "AI Software Compiler";
                pageSubtitle.textContent = "Compile Natural Language requirements directly to executing applications.";
            } else if (targetTab === "schemas-tab") {
                pageTitle.textContent = "Compiled AST & Schemas";
                pageSubtitle.textContent = "Browse structured layers generated by the compiler stages.";
                renderSchemaCode();
            } else if (targetTab === "validation-tab") {
                pageTitle.textContent = "Validation Mesh & Repair Engine";
                pageSubtitle.textContent = "Inspect semantic schema validation metrics and self-healing logs.";
            } else if (targetTab === "runtime-tab") {
                pageTitle.textContent = "Live Application Sandbox";
                pageSubtitle.textContent = "Interact with the dynamically compiled application using live SQLite records.";
                renderSandbox();
            }
        });
    });

    // --- Examples Loader ---
    document.getElementById("load-crm-example").addEventListener("click", () => {
        promptInput.value = "Build a CRM with login, contacts, dashboard, role-based access, and premium plan with payments. Admins can see analytics.";
    });
    
    document.getElementById("load-store-example").addEventListener("click", () => {
        promptInput.value = "Build an e-commerce platform with customer login, product catalog list page, shopping cart, checkout, payments, and admin product management.";
    });

    // --- Console Logger Helpers ---
    function clearConsole() {
        consoleLogs.innerHTML = "";
    }
    
    function logToConsole(message, type = "info") {
        const line = document.createElement("div");
        line.className = `console-line ${type}`;
        line.textContent = `[${new Date().toLocaleTimeString()}] ${message}`;
        consoleLogs.appendChild(line);
        consoleLogs.scrollTop = consoleLogs.scrollHeight;
    }

    // --- Schema Buttons Handler ---
    schemaBtns.forEach(btn => {
        btn.addEventListener("click", () => {
            schemaBtns.forEach(b => b.classList.remove("active"));
            btn.classList.add("active");
            selectedSchemaType = btn.getAttribute("data-schema");
            renderSchemaCode();
        });
    });

    function renderSchemaCode() {
        if (!compiledAppState) {
            schemaCodeBlock.textContent = JSON.stringify({ "message": "Compile an application first." }, null, 2);
            return;
        }
        
        let schemaData = {};
        let title = "";
        
        switch(selectedSchemaType) {
            case "ui":
                schemaData = compiledAppState.schema.ui;
                title = "UI Layout & Pages Schema";
                break;
            case "api":
                schemaData = compiledAppState.schema.api;
                title = "API Endpoints Route Schema";
                break;
            case "db":
                schemaData = compiledAppState.schema.db;
                title = "Database SQL Tables Schema";
                break;
            case "auth":
                schemaData = compiledAppState.schema.auth;
                title = "Role-Based Access (RBAC) Schema";
                break;
            case "rules":
                schemaData = compiledAppState.schema.business_rules;
                title = "Business Logic Policies";
                break;
        }
        
        schemaViewerTitle.textContent = title;
        schemaCodeBlock.textContent = JSON.stringify(schemaData, null, 2);
    }
    
    copySchemaBtn.addEventListener("click", () => {
        navigator.clipboard.writeText(schemaCodeBlock.textContent);
        const originalText = copySchemaBtn.innerHTML;
        copySchemaBtn.innerHTML = '<i class="fa-solid fa-check"></i> Copied!';
        setTimeout(() => {
            copySchemaBtn.innerHTML = originalText;
        }, 1500);
    });

    function normalizeRoute(route) {
        if (!route || typeof route !== "string") return "";
        let normalized = route.trim();
        if (!normalized.startsWith("/")) normalized = "/" + normalized;
        normalized = normalized.replace(/\s+/g, "-").toLowerCase();
        normalized = normalized.replace(/\/+/g, "/");
        if (normalized.length > 1 && normalized.endsWith("/")) {
            normalized = normalized.slice(0, -1);
        }
        return normalized;
    }

    function ensurePageSchema(page, index) {
        return {
            route: normalizeRoute(page.route || page.title || `/page-${index + 1}`),
            title: page.title || page.route || `Page ${index + 1}`,
            description: page.description || page.title || "Live compiled application page generated from the UI schema.",
            layout: page.layout || "default",
            components: Array.isArray(page.components) ? page.components : [],
            ...page
        };
    }

    async function waitForRender() {
        return new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)));
    }

    // --- Draw Intent Graph ---
    function renderIntentGraph(graph) {
        graphContainer.innerHTML = "";
        if (!graph || !graph.nodes || graph.nodes.length === 0) {
            graphContainer.innerHTML = `
                <div class="empty-placeholder">
                    <i class="fa-solid fa-network-wired"></i>
                    <p>Compile an application to visualize the IR dependency graph.</p>
                </div>`;
            return;
        }
        
        const wrapper = document.createElement("div");
        wrapper.className = "ir-graph-wrapper";
        
        graph.nodes.forEach(node => {
            const el = document.createElement("div");
            el.className = `graph-node ${node.type}`;
            
            let icon = "";
            if (node.type === "application") icon = '<i class="fa-solid fa-microchip"></i>';
            else if (node.type === "role") icon = '<i class="fa-solid fa-user-shield"></i>';
            else if (node.type === "feature") icon = '<i class="fa-solid fa-star"></i>';
            else if (node.type === "entity") icon = '<i class="fa-solid fa-database"></i>';
            
            el.innerHTML = `${icon} <span>${node.label}</span>`;
            wrapper.appendChild(el);
        });
        
        graphContainer.appendChild(wrapper);
    }

    // --- Validation Audit Log ---
    function renderValidationMesh(data) {
        valErrorsCount.textContent = data.validation_final.errors.length;
        valWarningsCount.textContent = data.validation_initial.warnings.length;
        
        // Remove styling first
        valStatusIcon.className = "val-icon";
        
        if (data.status === "SUCCESS") {
            valStatusText.textContent = "PASSED";
            valStatusIcon.classList.add("green");
            valStatusIcon.innerHTML = '<i class="fa-solid fa-circle-check"></i>';
        } else {
            valStatusText.textContent = "FAILED";
            valStatusIcon.classList.add("red");
            valStatusIcon.innerHTML = '<i class="fa-solid fa-triangle-exclamation"></i>';
        }
        
        auditLogList.innerHTML = "";
        
        // Render Initial Errors / Repairs
        let hasLogs = false;
        
        if (data.validation_initial.errors && data.validation_initial.errors.length > 0) {
            hasLogs = true;
            data.validation_initial.errors.forEach(err => {
                const item = document.createElement("div");
                item.className = "audit-item error";
                
                // Check if this error was repaired
                const repairedLog = data.repair_logs.find(log => log.error_code === err.code);
                
                item.innerHTML = `
                    <div class="audit-header">
                        <span class="audit-badge error">Initial Error</span>
                        <span class="audit-meta">Layer: ${err.layer} | Code: ${err.code}</span>
                    </div>
                    <div class="audit-msg">${err.message}</div>
                    ${repairedLog ? `
                    <div class="audit-action">
                        <i class="fa-solid fa-wrench"></i> <strong>Self-Healed:</strong> ${repairedLog.action_taken} (Status: ${repairedLog.status})
                    </div>
                    ` : `
                    <div class="audit-meta" style="color: var(--error); margin-top: 0.5rem;">
                        <i class="fa-solid fa-circle-xmark"></i> Repair engine could not automatically fix this mismatch.
                    </div>
                    `}
                `;
                auditLogList.appendChild(item);
            });
        }
        
        // Render warnings
        if (data.validation_initial.warnings && data.validation_initial.warnings.length > 0) {
            hasLogs = true;
            data.validation_initial.warnings.forEach(warn => {
                const item = document.createElement("div");
                item.className = "audit-item warning";
                
                const repairedLog = data.repair_logs.find(log => log.error_code === warn.code);
                
                item.innerHTML = `
                    <div class="audit-header">
                        <span class="audit-badge warning">Warning</span>
                        <span class="audit-meta">Layer: ${warn.layer} | Code: ${warn.code}</span>
                    </div>
                    <div class="audit-msg">${warn.message}</div>
                    ${repairedLog ? `
                    <div class="audit-action">
                        <i class="fa-solid fa-wrench"></i> <strong>Auto-Fixed:</strong> ${repairedLog.action_taken}
                    </div>
                    ` : ""}
                `;
                auditLogList.appendChild(item);
            });
        }
        
        if (!hasLogs) {
            auditLogList.innerHTML = `
                <div class="audit-item repair" style="border-left: 4px solid var(--success);">
                    <div class="audit-msg"><i class="fa-solid fa-circle-check" style="color: var(--success)"></i> Perfect compilation score! Zero validation errors or warnings detected in raw schemas.</div>
                </div>`;
        }
    }

    // --- Simulation Report ---
    function renderSimulationReport(sim) {
        simReportBox.innerHTML = "";
        if (!sim) {
            simReportBox.innerHTML = '<p class="help-text">No simulation ran yet.</p>';
            return;
        }
        
        const lines = [
            { label: "SQLite DB Creation", status: sim.database_creation === "SUCCESS" },
            { label: "API Route Validation", status: sim.api_routing === "SUCCESS" },
            { label: "RBAC Access Controls", status: sim.permission_checks === "SUCCESS" }
        ];
        
        lines.forEach(line => {
            const div = document.createElement("div");
            div.className = `sim-check-line ${line.status ? 'pass' : 'fail'}`;
            div.innerHTML = `
                <i class="fa-solid ${line.status ? 'fa-circle-check' : 'fa-circle-xmark'}"></i>
                <span><strong>${line.label}:</strong> ${line.status ? 'PASSED' : 'FAILED'}</span>
            `;
            simReportBox.appendChild(div);
        });
        
        const divider = document.createElement("div");
        divider.className = "divider";
        simReportBox.appendChild(divider);
        
        const findingsHeader = document.createElement("div");
        findingsHeader.style.fontWeight = "bold";
        findingsHeader.style.marginBottom = "0.25rem";
        findingsHeader.textContent = "Simulation Log:";
        simReportBox.appendChild(findingsHeader);
        
        sim.findings.forEach(find => {
            const p = document.createElement("p");
            p.style.color = "var(--text-secondary)";
            p.style.fontSize = "0.75rem";
            p.style.marginBottom = "0.25rem";
            p.textContent = `• ${find}`;
            simReportBox.appendChild(p);
        });
    }

    // --- Dynamic Live Sandbox Render ---
    runtimeRoleSelect.addEventListener("change", (e) => {
        activeUserRole = e.target.value;
        
        // Auto-authenticate standard profiles when switching roles in sandbox control panel
        mockJwtToken = "mock-jwt-token-xyz";
        
        if (compiledAppState) {
            const ui = compiledAppState.schema.ui || {};
            const rawPages = Array.isArray(ui.pages) ? ui.pages : [];
            const pages = rawPages.map((page, idx) => ensurePageSchema(page, idx));
            const dashboardRoute = pages.find(page => page.route === "/dashboard")?.route;
            activeRuntimeRoute = dashboardRoute || pages[0]?.route || "/login";
        }
        renderSandbox();
    });

    async function makeRuntimeRequest(url, method = "GET", body = null) {
        const headers = {
            "Content-Type": "application/json",
            "X-User-Role": activeUserRole
        };
        if (mockJwtToken) {
            headers["Authorization"] = `Bearer ${mockJwtToken}`;
        }
        
        const options = { method, headers };
        if (body) {
            options.body = JSON.stringify(body);
        }
        
        const res = await fetch(url, options);
        if (!res.ok) {
            const data = await res.json();
            throw new Error(data.detail || "Request failed.");
        }
        return res.json();
    }

    // Sample data for the interactive sandbox
    const sampleData = {
        users: [
            { id: 1, email: "admin@builder.ai", name: "Alice Johnson", role: "Admin", created_at: "2024-01-10", status: "Active" },
            { id: 2, email: "sales@builder.ai", name: "Bob Smith", role: "SalesManager", created_at: "2024-02-15", status: "Active" },
            { id: 3, email: "user@builder.ai", name: "Carol Davis", role: "User", created_at: "2024-03-05", status: "Active" }
        ],
        contacts: [
            { id: 1, name: "Acme Corp", email: "contact@acme.com", phone: "555-0101", company: "Acme Inc", status: "Prospect" },
            { id: 2, name: "Tech Solutions", email: "sales@techsol.com", phone: "555-0102", company: "Tech Solutions", status: "Client" },
            { id: 3, name: "Global Industries", email: "info@global.com", phone: "555-0103", company: "Global Industries", status: "Client" },
            { id: 4, name: "Innovation Labs", email: "contact@innolab.com", phone: "555-0104", company: "Innovation Labs", status: "Lead" }
        ],
        products: [
            { id: 1, name: "Pro Starter Pack", sku: "PSP-001", price: 29.99, category: "Subscription", stock: 150, rating: 4.5 },
            { id: 2, name: "Enterprise Bundle", sku: "EB-001", price: 99.99, category: "Subscription", stock: 75, rating: 4.8 },
            { id: 3, name: "Premium Plus", sku: "PP-001", price: 49.99, category: "Upgrade", stock: 200, rating: 4.7 },
            { id: 4, name: "Lite Free Tier", sku: "LFT-001", price: 0.00, category: "Free", stock: -1, rating: 4.2 }
        ],
        orders: [
            { id: 101, customer: "Acme Corp", amount: 1299.99, status: "Completed", date: "2024-11-28", items: 3 },
            { id: 102, customer: "Tech Solutions", amount: 599.99, status: "Pending", date: "2024-11-29", items: 2 },
            { id: 103, customer: "Global Industries", amount: 2499.99, status: "Completed", date: "2024-11-27", items: 5 }
        ],
        analytics: {
            total_revenue: 45230,
            growth: 24,
            recent_sales: [
                { id: 1, amount: 1200, date: "Nov 28" },
                { id: 2, amount: 950, date: "Nov 29" },
                { id: 3, amount: 1500, date: "Nov 30" },
                { id: 4, amount: 800, date: "Dec 1" },
                { id: 5, amount: 1300, date: "Dec 2" }
            ]
        }
    };

    async function renderSandbox() {
        if (!compiledAppState) {
            sandboxViewport.innerHTML = `
                <div class="viewport-empty">
                    <i class="fa-solid fa-play-circle"></i>
                    <p>Run compilation first to load the dynamic live application runtime.</p>
                </div>`;
            return;
        }

        const ui = compiledAppState.schema.ui || {};
        const rawPages = Array.isArray(ui.pages) ? ui.pages : [];
        let pages = rawPages.map((page, idx) => ensurePageSchema(page, idx));

        const navigationPages = Array.isArray(ui.navigation) ? ui.navigation.map((nav, idx) => ({
            route: normalizeRoute(nav.route || nav.label || `/nav-${idx + 1}`),
            title: nav.label || nav.route || `Page ${idx + 1}`,
            description: nav.description || "",
            layout: "default",
            components: []
        })) : [];

        if (pages.length === 0 && navigationPages.length > 0) {
            pages = navigationPages;
        }

        const hasLoginPage = pages.some(page => page.route === "/login");
        const activeClassForLogin = activeRuntimeRoute === "/login" ? "active" : "";
        let navHtml = "";

        if (!mockJwtToken) {
            navHtml += `<span class="rt-nav-link ${activeClassForLogin}" data-route="/login"><i class="fa-solid fa-sign-in-alt"></i> Login</span>`;
        }

        if (pages.length === 0) {
            navHtml += `<span class="rt-nav-link active" data-route="/empty"><i class="fa-solid fa-file-circle-exclamation"></i> No pages configured</span>`;
        } else {
            pages.forEach(page => {
                const activeClass = activeRuntimeRoute === page.route ? "active" : "";
                const icon = page.props?.icon || "fa-file-lines";
                navHtml += `<span class="rt-nav-link ${activeClass}" data-route="${page.route}"><i class="fa-solid ${icon}"></i> ${page.title}</span>`;
            });
        }

        if (mockJwtToken) {
            navHtml += `<span class="rt-nav-link" id="rt-logout-btn"><i class="fa-solid fa-sign-out-alt"></i> Logout</span>`;
        }

        const validRoutes = ["/login", ...pages.map(page => page.route)];
        if (!validRoutes.includes(activeRuntimeRoute)) {
            const dashboardRoute = pages.find(page => page.route === "/dashboard")?.route;
            activeRuntimeRoute = mockJwtToken ? (dashboardRoute || pages[0]?.route || "/login") : "/login";
        }

        sandboxViewport.innerHTML = `
            <div class="rt-layout">
                <div class="rt-navbar">
                    <div class="rt-brand"><i class="fa-solid fa-rocket"></i> ${compiledAppState.intent.application_name}</div>
                    <div class="rt-nav-links">${navHtml}</div>
                    <div class="rt-role-badge"><i class="fa-solid fa-user-circle"></i> ${activeUserRole}</div>
                </div>
                <div class="rt-body" id="rt-body-content">
                    <div class="loader-box" style="margin-top: 5rem;"><div class="spinner"></div></div>
                </div>
            </div>
        `;

        const links = sandboxViewport.querySelectorAll(".rt-nav-link");
        links.forEach(link => {
            link.addEventListener("click", () => {
                const route = normalizeRoute(link.getAttribute("data-route"));
                if (link.id === "rt-logout-btn") {
                    mockJwtToken = null;
                    activeRuntimeRoute = "/login";
                    renderSandbox();
                } else if (route) {
                    activeRuntimeRoute = route;
                    renderSandbox();
                }
            });
        });

        const rtBody = document.getElementById("rt-body-content");
        if (activeRuntimeRoute === "/login") {
            renderLoginPage(rtBody);
            return;
        }

        if (!mockJwtToken) {
            rtBody.innerHTML = `<div class="rt-card" style="text-align: center; margin-top: 3rem;"><h3>Please login to continue</h3></div>`;
            activeRuntimeRoute = "/login";
            renderSandbox();
            return;
        }

        const currentPage = pages.find(page => page.route === activeRuntimeRoute);
        if (!currentPage) {
            rtBody.innerHTML = `<div class="rt-card" style="text-align: center; margin-top: 3rem;"><h3>Page not found for route ${activeRuntimeRoute}</h3></div>`;
            return;
        }

        await renderPageFromSchema(rtBody, currentPage);
    }

    async function renderPageFromSchema(container, page) {
        container.innerHTML = "";
        const wrapper = document.createElement("div");
        wrapper.className = "rt-page-wrapper";
        wrapper.innerHTML = `
            <div class="rt-page-header">
                <h2><i class="fa-solid fa-window-maximize"></i> ${page.title || page.route}</h2>
                <p>${page.description || "Live compiled application page generated from the UI schema."}</p>
            </div>
        `;

        const content = document.createElement("div");
        content.className = "rt-page-content";

        if (!page.components || page.components.length === 0) {
            content.innerHTML = `<div class="rt-card" style="text-align:center;">This page has no components defined in the compiled schema.</div>`;
        } else {
            for (const comp of page.components) {
                const compWrapper = document.createElement("div");
                compWrapper.className = "rt-component-card";
                compWrapper.innerHTML = `
                    <div class="rt-component-header">
                        <div>
                            <h4>${comp.label || comp.type}</h4>
                            <small>${comp.type}</small>
                        </div>
                    </div>
                    <div class="rt-component-body" id="component-${comp.id}">
                        <div class="loader-box"><div class="spinner"></div></div>
                    </div>
                `;
                content.appendChild(compWrapper);
                const target = compWrapper.querySelector(`#component-${comp.id}`);
                await loadSandboxComponent(comp, target);
            }
        }

        wrapper.appendChild(content);
        container.appendChild(wrapper);
    }

    function renderDemoPage(container, route) {
        let content = "";

        if (route === "/dashboard") {
            content = `
                <div class="rt-page-header">
                    <h2><i class="fa-solid fa-chart-line"></i> Dashboard</h2>
                    <p>Welcome back! Here's your business overview.</p>
                </div>
                <div class="rt-stats-grid">
                    <div class="rt-stat-card">
                        <div class="stat-icon"><i class="fa-solid fa-users"></i></div>
                        <div class="stat-content">
                            <div class="stat-value">12</div>
                            <div class="stat-label">Active Contacts</div>
                        </div>
                    </div>
                    <div class="rt-stat-card">
                        <div class="stat-icon"><i class="fa-solid fa-shopping-cart"></i></div>
                        <div class="stat-content">
                            <div class="stat-value">8</div>
                            <div class="stat-label">Recent Orders</div>
                        </div>
                    </div>
                    <div class="rt-stat-card">
                        <div class="stat-icon"><i class="fa-solid fa-dollar-sign"></i></div>
                        <div class="stat-content">
                            <div class="stat-value">$45.2K</div>
                            <div class="stat-label">Total Revenue</div>
                        </div>
                    </div>
                    <div class="rt-stat-card">
                        <div class="stat-icon"><i class="fa-solid fa-trending-up"></i></div>
                        <div class="stat-content">
                            <div class="stat-value">+24%</div>
                            <div class="stat-label">Growth Rate</div>
                        </div>
                    </div>
                </div>

                <div class="rt-grid">
                    <div class="rt-card" style="grid-column: span 2;">
                        <h4><i class="fa-solid fa-chart-bar"></i> Revenue Trend</h4>
                        <div class="chart-container">
                            <div class="chart-bar-group">
                                ${sampleData.analytics.recent_sales.map(s => 
                                    `<div class="chart-bar" title="$${s.amount}">
                                        <div class="bar-fill" style="height: ${(s.amount / 1500) * 100}%"></div>
                                        <div class="bar-label">${s.date}</div>
                                    </div>`
                                ).join('')}
                            </div>
                        </div>
                    </div>

                    <div class="rt-card">
                        <h4><i class="fa-solid fa-list"></i> Recent Orders</h4>
                        <div class="mini-table">
                            ${sampleData.orders.slice(0, 3).map(o => `
                                <div class="mini-row">
                                    <span>#${o.id}</span>
                                    <span>${o.customer}</span>
                                    <span class="badge badge-${o.status === 'Completed' ? 'success' : 'warning'}">${o.status}</span>
                                </div>
                            `).join('')}
                        </div>
                    </div>
                </div>
            `;
        } else if (route === "/contacts") {
            content = `
                <div class="rt-page-header">
                    <h2><i class="fa-solid fa-address-book"></i> Contacts Management</h2>
                    <button class="rt-btn-add" id="add-contact-btn"><i class="fa-solid fa-plus"></i> Add Contact</button>
                </div>
                <div class="rt-card">
                    <div class="rt-table-wrapper">
                        <table class="rt-table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Company</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                ${sampleData.contacts.map(c => `
                                    <tr>
                                        <td><strong>${c.name}</strong></td>
                                        <td>${c.email}</td>
                                        <td>${c.phone}</td>
                                        <td>${c.company}</td>
                                        <td><span class="badge badge-${c.status === 'Client' ? 'success' : c.status === 'Prospect' ? 'info' : 'warning'}">${c.status}</span></td>
                                        <td>
                                            <button class="rt-btn-sm rt-btn-edit" title="Edit"><i class="fa-solid fa-edit"></i></button>
                                            <button class="rt-btn-sm rt-btn-delete" title="Delete"><i class="fa-solid fa-trash"></i></button>
                                        </td>
                                    </tr>
                                `).join('')}
                            </tbody>
                        </table>
                    </div>
                </div>

                <div id="contact-modal" class="rt-modal" style="display: none;">
                    <div class="rt-modal-content">
                        <div class="rt-modal-header">
                            <h3>Add New Contact</h3>
                            <button class="rt-modal-close">&times;</button>
                        </div>
                        <form id="contact-form" class="rt-form">
                            <div class="rt-form-group">
                                <label>Name</label>
                                <input type="text" class="rt-input" name="name" required>
                            </div>
                            <div class="rt-form-group">
                                <label>Email</label>
                                <input type="email" class="rt-input" name="email" required>
                            </div>
                            <div class="rt-form-group">
                                <label>Phone</label>
                                <input type="tel" class="rt-input" name="phone" required>
                            </div>
                            <div class="rt-form-group">
                                <label>Company</label>
                                <input type="text" class="rt-input" name="company" required>
                            </div>
                            <div class="rt-form-group">
                                <label>Status</label>
                                <select class="rt-input" name="status">
                                    <option>Lead</option>
                                    <option>Prospect</option>
                                    <option>Client</option>
                                </select>
                            </div>
                            <div class="rt-form-actions">
                                <button type="submit" class="rt-btn rt-btn-primary">Save Contact</button>
                                <button type="button" class="rt-btn rt-btn-secondary rt-modal-close">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            `;
        } else if (route === "/products") {
            content = `
                <div class="rt-page-header">
                    <h2><i class="fa-solid fa-box"></i> Product Catalog</h2>
                    <button class="rt-btn-add" id="add-product-btn"><i class="fa-solid fa-plus"></i> Add Product</button>
                </div>
                <div class="rt-products-grid">
                    ${sampleData.products.map(p => `
                        <div class="rt-product-card">
                            <div class="product-header">
                                <h4>${p.name}</h4>
                                <span class="product-sku">${p.sku}</span>
                            </div>
                            <div class="product-content">
                                <div class="product-price">$${p.price.toFixed(2)}</div>
                                <div class="product-meta">
                                    <span class="badge">${p.category}</span>
                                    <span class="stock-indicator ${p.stock > 100 ? 'in-stock' : p.stock > 0 ? 'low-stock' : 'out-of-stock'}">
                                        ${p.stock > 0 ? `${p.stock} in stock` : 'Out of stock'}
                                    </span>
                                </div>
                                <div class="product-rating">
                                    <i class="fa-solid fa-star"></i> ${p.rating} / 5.0
                                </div>
                            </div>
                            <div class="product-actions">
                                <button class="rt-btn rt-btn-sm rt-btn-primary">View</button>
                                <button class="rt-btn rt-btn-sm rt-btn-secondary">Edit</button>
                            </div>
                        </div>
                    `).join('')}
                </div>
            `;
        } else if (route === "/orders") {
            content = `
                <div class="rt-page-header">
                    <h2><i class="fa-solid fa-receipt"></i> Orders</h2>
                    <button class="rt-btn-add" id="create-order-btn"><i class="fa-solid fa-plus"></i> New Order</button>
                </div>
                <div class="rt-card">
                    <div class="rt-table-wrapper">
                        <table class="rt-table">
                            <thead>
                                <tr>
                                    <th>Order ID</th>
                                    <th>Customer</th>
                                    <th>Amount</th>
                                    <th>Items</th>
                                    <th>Date</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                ${sampleData.orders.map(o => `
                                    <tr>
                                        <td><strong>#${o.id}</strong></td>
                                        <td>${o.customer}</td>
                                        <td class="currency">$${o.amount.toFixed(2)}</td>
                                        <td>${o.items}</td>
                                        <td>${o.date}</td>
                                        <td><span class="badge badge-${o.status === 'Completed' ? 'success' : 'warning'}">${o.status}</span></td>
                                        <td>
                                            <button class="rt-btn-sm rt-btn-view" title="View"><i class="fa-solid fa-eye"></i></button>
                                            <button class="rt-btn-sm rt-btn-edit" title="Edit"><i class="fa-solid fa-edit"></i></button>
                                        </td>
                                    </tr>
                                `).join('')}
                            </tbody>
                        </table>
                    </div>
                </div>
            `;
        }

        container.innerHTML = content;

        // Add event listeners for modal/actions
        const addContactBtn = container.querySelector("#add-contact-btn");
        const addProductBtn = container.querySelector("#add-product-btn");
        const createOrderBtn = container.querySelector("#create-order-btn");

        if (addContactBtn) {
            addContactBtn.addEventListener("click", () => {
                const modal = container.querySelector("#contact-modal");
                modal.style.display = "flex";
                setupModalListeners(container);
            });
        }

        if (addProductBtn) {
            addProductBtn.addEventListener("click", () => {
                alert("Product addition feature would open a form here!");
            });
        }

        if (createOrderBtn) {
            createOrderBtn.addEventListener("click", () => {
                alert("Order creation feature would open a checkout form here!");
            });
        }

        // Setup modal close buttons
        setupModalListeners(container);
    }

    function setupModalListeners(container) {
        const closeButtons = container.querySelectorAll(".rt-modal-close");
        closeButtons.forEach(btn => {
            btn.addEventListener("click", () => {
                const modal = btn.closest(".rt-modal");
                if (modal) modal.style.display = "none";
            });
        });

        const forms = container.querySelectorAll("#contact-form");
        forms.forEach(form => {
            form.addEventListener("submit", (e) => {
                e.preventDefault();
                alert("Contact saved successfully!");
                const modal = form.closest(".rt-modal");
                if (modal) modal.style.display = "none";
                renderSandbox();
            });
        });
    }

    function renderLoginPage(container) {
        container.innerHTML = `
            <div class="rt-card" style="max-width: 380px; margin: 3rem auto 0 auto;">
                <h4>User Login Gateway</h4>
                <div id="login-error-msg" style="color: var(--error); font-size: 0.8rem; margin-bottom: 0.5rem;"></div>
                <form id="rt-login-form">
                    <div class="rt-form-group">
                        <label>Select Demo Account Profile</label>
                        <select id="login-preset-select" class="form-control">
                            <option value="admin@builder.ai|admin123|Admin">Admin User (admin@builder.ai)</option>
                            <option value="sales@builder.ai|sales123|SalesManager">Sales Manager (sales@builder.ai)</option>
                            <option value="user@builder.ai|user123|User">Standard User (user@builder.ai)</option>
                        </select>
                    </div>
                    <div class="rt-form-group">
                        <label>Email Address</label>
                        <input type="email" id="login-email-input" class="rt-input" value="admin@builder.ai">
                    </div>
                    <div class="rt-form-group">
                        <label>Password</label>
                        <input type="password" id="login-pass-input" class="rt-input" value="admin123">
                    </div>
                    <button type="submit" class="rt-submit-btn" style="margin-top: 1rem;">Authenticate Session</button>
                </form>
            </div>
        `;

        // Handle preset changes
        const preset = document.getElementById("login-preset-select");
        preset.addEventListener("change", (e) => {
            const [email, password] = e.target.value.split("|");
            document.getElementById("login-email-input").value = email;
            document.getElementById("login-pass-input").value = password;
        });

        const form = document.getElementById("rt-login-form");
        form.addEventListener("submit", async (e) => {
            e.preventDefault();
            const email = document.getElementById("login-email-input").value;
            const password = document.getElementById("login-pass-input").value;
            const errDiv = document.getElementById("login-error-msg");
            
            try {
                const res = await makeRuntimeRequest("/api/auth/login", "POST", { email, password });
                mockJwtToken = res.token;
                activeUserRole = res.role;
                runtimeRoleSelect.value = res.role;

                const ui = compiledAppState?.schema?.ui || {};
                const successfulRoute = normalizeRoute(
                    ui.pages?.find(page => normalizeRoute(page.route) === "/dashboard")?.route ||
                    ui.pages?.[0]?.route ||
                    ui.navigation?.[0]?.route ||
                    "/dashboard"
                );
                activeRuntimeRoute = successfulRoute || "/dashboard";
                renderSandbox();
            } catch (err) {
                errDiv.textContent = err.message;
            }
        });
    }

    async function loadSandboxComponent(comp, container) {
        const apiRoute = comp.props.api_route;
        
        try {
            // RENDER TABLE COMPONENT
            if (comp.type === "table") {
                if (!apiRoute) {
                    container.innerHTML = "<p class='help-text'>No table source endpoint defined.</p>";
                    return;
                }
                
                // Fetch dynamic SQLite records
                const data = await makeRuntimeRequest(apiRoute);
                const cols = comp.props.columns || ["id"];
                
                let headersHtml = "";
                cols.forEach(c => headersHtml += `<th style="text-transform: capitalize;">${c}</th>`);
                headersHtml += "<th>Actions</th>";
                
                let rowsHtml = "";
                if (data && data.length > 0) {
                    data.forEach(row => {
                        let rowCells = "";
                        cols.forEach(c => {
                            rowCells += `<td>${row[c] !== undefined ? row[c] : ""}</td>`;
                        });
                        rowCells += `<td><button class="rt-btn-danger" data-id="${row.id}"><i class="fa-solid fa-trash"></i></button></td>`;
                        rowsHtml += `<tr>${rowCells}</tr>`;
                    });
                } else {
                    rowsHtml = `<tr><td colspan="${cols.length + 1}" style="text-align: center; color: var(--text-muted)">No records found. database table is currently empty.</td></tr>`;
                }
                
                container.innerHTML = `
                    <div class="rt-table-wrapper">
                        <table class="rt-table">
                            <thead><tr>${headersHtml}</tr></thead>
                            <tbody>${rowsHtml}</tbody>
                        </table>
                    </div>
                `;
                
                // Register delete action
                const delBtns = container.querySelectorAll(".rt-btn-danger");
                delBtns.forEach(btn => {
                    btn.addEventListener("click", async () => {
                        const id = btn.getAttribute("data-id");
                        try {
                            await makeRuntimeRequest(`${apiRoute}/${id}`, "DELETE");
                            renderSandbox();
                        } catch (err) {
                            alert(err.message);
                        }
                    });
                });
            }
            
            // RENDER FORM COMPONENT
            else if (comp.type === "form") {
                const fields = comp.props.fields || ["name"];
                const action = comp.props.action;
                
                // Map UI form actions to standard API endpoints
                // e.g. action "create_contact" -> POST /api/contacts
                let submitRoute = "/api/contacts";
                if (action === "process_payment" || action === "upgrade") {
                    submitRoute = "/api/billing/upgrade";
                } else if (action === "checkout") {
                    submitRoute = "/api/orders";
                }
                
                let fieldsHtml = "";
                fields.forEach(f => {
                    const inputType = f.includes("password") ? "password" : f.includes("amount") || f.includes("price") ? "number" : "text";
                    fieldsHtml += `
                        <div class="rt-form-group">
                            <label>${f.replace('_', ' ')}</label>
                            <input type="${inputType}" name="${f}" class="rt-input" required>
                        </div>
                    `;
                });
                
                container.innerHTML = `
                    <form class="rt-dynamic-form">
                        ${fieldsHtml}
                        <button type="submit" class="rt-submit-btn">${comp.label}</button>
                    </form>
                `;
                
                const form = container.querySelector(".rt-dynamic-form");
                form.addEventListener("submit", async (e) => {
                    e.preventDefault();
                    const formData = {};
                    const inputs = form.querySelectorAll("input");
                    inputs.forEach(i => {
                        formData[i.name] = i.type === "number" ? parseFloat(i.value) : i.value;
                    });
                    
                    // Special Mock IDs mapping if tables need creation credentials
                    if (submitRoute === "/api/contacts" && mockJwtToken) {
                        formData["created_by"] = 1; 
                    }
                    
                    try {
                        const res = await makeRuntimeRequest(submitRoute, "POST", formData);
                        alert(res.message || "Record submitted successfully!");
                        renderSandbox();
                    } catch (err) {
                        alert(err.message);
                    }
                });
            }
            
            // RENDER WIDGET STATS OR CHART COMPONENT
            else if (comp.type === "widget" || comp.type === "chart") {
                if (!apiRoute) {
                    container.innerHTML = "<p class='help-text'>No metric endpoint defined.</p>";
                    return;
                }
                
                const data = await makeRuntimeRequest(apiRoute);
                
                if (comp.type === "widget") {
                    container.innerHTML = `
                        <div class="rt-stat-box">
                            <div class="val">${data.count !== undefined ? data.count : data.total_revenue || 0}</div>
                            <div class="lbl">${comp.label}</div>
                        </div>
                    `;
                } else {
                    // Render premium chart representation
                    container.innerHTML = `
                        <div class="rt-stat-box" style="text-align: left;">
                            <div class="val">$${data.total_revenue} <span style="font-size: 0.85rem; color: var(--success); font-weight: normal;">+${data.growth}% MoM</span></div>
                            <div class="lbl" style="margin-bottom: 0.5rem;">Simulating database points...</div>
                            <div style="display: flex; gap: 0.4rem; height: 60px; align-items: flex-end; padding-top: 0.5rem;">
                                ${Array.isArray(data.recent_sales) ? data.recent_sales.map(s => `<div style="flex:1; background-color:var(--primary); height:${(s.amount / 1500) * 100}%; border-radius: 4px 4px 0 0;" title="$${s.amount}"></div>`).join('') : ''}
                            </div>
                        </div>
                    `;
                }
            }

            else if (comp.type === "button" || comp.type === "link") {
                const action = comp.props?.action || "";
                container.innerHTML = `<button class="rt-submit-btn">${comp.label}</button>`;
                const btn = container.querySelector("button");
                btn.addEventListener("click", () => {
                    if (action === "process_payment" || action === "upgrade") {
                        alert("This action would process a payment or upgrade in a real application.");
                    } else if (action === "login") {
                        activeRuntimeRoute = "/login";
                        renderSandbox();
                    } else {
                        alert(`Action triggered: ${action || comp.label}`);
                    }
                });
            }

            else if (["text", "paragraph", "description"].includes(comp.type)) {
                const contentText = comp.props?.text || comp.props?.content || comp.label || "Text content not available.";
                container.innerHTML = `<div class="rt-card"><p>${contentText}</p></div>`;
            }

            else if (comp.type === "list") {
                const items = Array.isArray(comp.props?.items) ? comp.props.items : [];
                container.innerHTML = `
                    <div class="rt-card">
                        <ul>${items.map(item => `<li>${item}</li>`).join("")}</ul>
                    </div>`;
            }

            else {
                const fallbackText = comp.props?.text || comp.props?.content || comp.label || `Unsupported component type: ${comp.type}`;
                container.innerHTML = `
                    <div class="rt-card">
                        <p>${fallbackText}</p>
                    </div>`;
            }
        } catch (err) {
            container.innerHTML = `<div style="color: var(--error); font-size: 0.85rem;"><i class="fa-solid fa-circle-exclamation"></i> Error: ${err.message}</div>`;
        }
    }

    // --- Run Compilation Pipeline ---
    compileBtn.addEventListener("click", async () => {
        const prompt = promptInput.value.trim();
        if (!prompt) {
            alert("Please enter an application prompt before compiling.");
            return;
        }

        loadingOverlay.style.display = "flex";
        loadingTitle.textContent = "Compiling Application...";

        // Define visual progress stages with realistic, staggered timing (800ms per stage)
        const visualSteps = [
            { subtitle: "Stage 1: Intent Extraction Layer...", log: "Stage 1: Parsing natural language user intent..." },
            { subtitle: "Stage 2: Graph Builder (Intermediate Representation)...", log: "Stage 2: Building compiler AST Intent Graph..." },
            { subtitle: "Stage 3: System Design / Architecture Planner...", log: "Stage 3: Planning system architecture and access matrices..." },
            { subtitle: "Stage 4: Schema Generator...", log: "Stage 4: Synthesizing UI configs, API routes, and DB models..." },
            { subtitle: "Stage 5: Validation Mesh...", log: "Stage 5: Verifying cross-layer API & DB referential contracts..." }
        ];

        try {
            // Trigger API request in parallel
            const apiPromise = fetch("/api/generate", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ prompt })
            });

            // Display visual progress stages one by one
            for (const step of visualSteps) {
                loadingSubtitle.textContent = step.subtitle;
                logToConsole(step.log, "info");
                await new Promise(resolve => setTimeout(resolve, 800));
            }

            // Monitor api completion state
            let apiResolved = false;
            let response = null;
            let apiError = null;

            apiPromise.then(res => {
                apiResolved = true;
                response = res;
            }).catch(err => {
                apiResolved = true;
                apiError = err;
            });

            // Advance through Stage 6 & 7 if the API is still processing
            let currentExtraStage = 6;
            while (!apiResolved) {
                if (currentExtraStage === 6) {
                    loadingSubtitle.textContent = "Stage 6: Repair Engine (Auto-healing)...";
                    logToConsole("Stage 6: Running auto-healing structural integrity checks...", "info");
                } else if (currentExtraStage === 7) {
                    loadingSubtitle.textContent = "Stage 7: Execution Simulator...";
                    logToConsole("Stage 7: Simulating database initialization & routing tables...", "info");
                } else {
                    loadingSubtitle.textContent = "Finalizing compilation environment...";
                }
                currentExtraStage++;
                await new Promise(resolve => setTimeout(resolve, 1000));
            }

            if (apiError) {
                throw apiError;
            }

            if (!response.ok) {
                throw new Error("Compilation server failed to respond.");
            }

            const data = await response.json();
            compiledAppState = data;

            // Log results to console
            logToConsole(`Stage 1 Intent Extracted: App Type: '${data.intent.application_name}'`, "success");
            logToConsole(`Stage 2 Graph created: ${data.graph.nodes.length} nodes, ${data.graph.edges.length} edges`, "success");
            logToConsole(`Stage 3 Architecture: ${data.design.modules.length} active modules planned`, "success");

            // Check initial validation
            if (data.validation_initial.is_valid) {
                logToConsole("Stage 5 Validation Mesh: PASSED with 0 errors.", "success");
            } else {
                logToConsole(`Stage 5 Validation Mesh: FAILED with ${data.validation_initial.errors.length} errors. Booting Repair Engine...`, "warning");
                data.repair_logs.forEach(log => {
                    logToConsole(`Stage 6 Repair Engine: [${log.layer}] Fixed error: ${log.action_taken}`, "success");
                });

                if (data.repair_success) {
                    logToConsole("Stage 6 Repair Engine: Schema healed successfully. Re-running validation... PASSED.", "success");
                } else {
                    logToConsole("Stage 6 Repair Engine: Mismatches remain unresolved. Manual intervention required.", "error");
                }
            }

            logToConsole(`Stage 7 Execution Simulator: SQLite DB Status: ${data.simulator_report.database_creation}`, data.simulator_report.status === "PASS" ? "success" : "error");

            if (data.live_runtime_active) {
                logToConsole("Sandbox Runtime successfully launched on local dev server.", "success");
            }

            // Render everything
            renderIntentGraph(data.graph);
            renderValidationMesh(data);
            renderSimulationReport(data.simulator_report);
            renderSandbox();

            // Reset runtime state to show login page first
            activeRuntimeRoute = "/login";
            mockJwtToken = null;

            // Move status indicator to compiled
            const indicator = document.getElementById("compiler-status-indicator");
            indicator.innerHTML = '<span class="status-dot green"></span> Compiled Ready';

            logToConsole("Compilation Complete. Sandboxed workspace loaded.", "system");
        } catch (err) {
            logToConsole(`Compilation Error: ${err.message}`, "error");
            alert(err.message);
        } finally {
            loadingOverlay.style.display = "none";
        }
    });

});
